spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tramites-backend
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: tramitesdb
  web:
    cors:
      allowed-origins: "*"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucket-name: ${AWS_BUCKET_NAME}

logging:
  level:
    org:
      springframework:
        security: TRACE